### ISSUE TITLE
Quality control

### ISSUE THREAD

**Issue by huangjy-pku** [FuxiaoLiu/LRV-Instruction#10]
Hello, awesome work on automatic data generation! I believe the high quality of generated data, as mentioned in your paper (91% reasonable for instruction and 85% accurate for response). Despite the high quality, have you tried any further methods to filter the generated data? In particular, when running large-scale data generation, manual checking is infeasible and how to control the quality of the final dataset becomes a noticeable issue.

**Comment by FuxiaoLiu** [comment]
Thanks for your comments. We manually check the training set again and update the training set.
