### ISSUE TITLE
Chart images

### ISSUE THREAD

**Issue by John-Ge** [FuxiaoLiu/LRV-Instruction#13]
Thank you for your awesome wor. I notice you release a chart dataset. How to download the chart images?

**Comment by FuxiaoLiu** [comment]
I will release the images by the weekend.

**Comment by John-Ge** [comment]
Hello, I notice you have released a MMC benchmark for chart images. But I can find the download link for chart images in LRV homepage. Could you please update the README.md or put the download link here? Thank you for your reply.

**Comment by FuxiaoLiu** [comment]
I just update the chart instruction and chart images links in the repo. Please check! If you have questions, please let me know.

**Comment by John-Ge** [comment]
Thank you! I have seen the download link. Thank you for you awesome work!

**Comment by FuxiaoLiu** [comment]
> Thank you! I have seen the download link. Thank you for you awesome work!

I just update the chart instructions data and images since the old version has some mismatch.
