### ISSUE TITLE
Cannot reproduce the result on MME leaderboard

### ISSUE THREAD

**Issue by aiiph4** [FuxiaoLiu/LRV-Instruction#15]
Hi. I am trying to obtain the result of LRV-Instruction on MME benchmark, which is 1299.78 on Perception. However, I can only get around 600-700 score.

Specifically, I follow the instruction in https://github.com/FuxiaoLiu/LRV-Instruction/blob/main/utils/README.md. I modify the code in `utils/inference.py` to evaluate on MME. I leave the prompt and generation config unchanged. The base-model is downloaded from https://huggingface.co/MAGAer13/mplug-owl-llama-7b-ft. 

Could you please kindly tell me how can I obtain the result on MME benchmark?

**Comment by FuxiaoLiu** [comment]
This might because our model is sensitive to the prompt in the MME. We just remove the "please answer yes or no" in the prompt and release the ability of the model to answer the question. If the key words like "no", "not" in the answers. We regard it as the 'no' and then calculate the result. If you have more questions, please let me know.

**Comment by Haoye17** [comment]
Hi, I followed your instructions to remove "Please answer yes or no."  in the questions in MME, and apply your strategy to map answers into yes/no, but we still cannot reproduce the results shown in your paper. Our results are as follows:
=========== Perception ===========
total score: 1084.4144657863146 

	 existence  score: 153.33333333333334
	 count  score: 76.66666666666667
	 position  score: 81.66666666666667
	 color  score: 81.66666666666667
	 posters  score: 101.36054421768708
	 celebrity  score: 86.47058823529412
	 scene  score: 144.75
	 landmark  score: 129.5
	 artwork  score: 96.5
	 OCR  score: 132.5


=========== Cognition ===========
total score: 294.6428571428571 

	 commonsense_reasoning  score: 87.14285714285714
	 numerical_calculation  score: 52.5
	 text_translation  score: 92.5
	 code_reasoning  score: 62.5

Is there anything we can do to reproduce your results? Thanks!
