### ISSUE TITLE
Cannot reproduce MME results on mPLUG-OWL version

### ISSUE THREAD

**Issue by Haoye17** [FuxiaoLiu/LRV-Instruction#16]
Hi, I followed your instructions to remove "Please answer yes or no." in the questions in MME, and apply your strategy to map answers into yes/no, but we still cannot reproduce the results shown in your paper. Our results are as follows:
```
=========== Perception ===========
total score: 1084.4144657863146

 existence  score: 153.33333333333334
 count  score: 76.66666666666667
 position  score: 81.66666666666667
 color  score: 81.66666666666667
 posters  score: 101.36054421768708
 celebrity  score: 86.47058823529412
 scene  score: 144.75
 landmark  score: 129.5
 artwork  score: 96.5
 OCR  score: 132.5
=========== Cognition ===========
total score: 294.6428571428571

 commonsense_reasoning  score: 87.14285714285714
 numerical_calculation  score: 52.5
 text_translation  score: 92.5
 code_reasoning  score: 62.5
```
Is there anything we can do to reproduce your results? Thanks!

**Comment by Hyperwjf** [comment]
Hello, I'm now facing an issue with loading the mPLUG-Owl finetuned model. Could you please tell me how to load the pytorch_model.bin weights provided by the author?
