### ISSUE TITLE
Failed Loading for mPLUG-Owl finetuned model

### ISSUE THREAD

**Issue by GUOGUO-lab** [FuxiaoLiu/LRV-Instruction#18]
Hi there, thanks for your work and guide.

I tried to finetune mplug-owl (by train_it.sh, this script uses lora) and get the output files. 
And I got some small model and config files (like "adapter_model.bin", each smaller than 50m).
Then I tried to load the lora model (after replace the original model_worker.py by yours).
But I still encounter the problem of "Missing key(s) in state_dict:  xxxxxx; Unexpected key(s) in state_dict: xxxxxx".

I found that your mplug lora model is named pytorch_model.bin, but I only got "adapter_model.bin" after finetuning.
I also noticed that the mplug lora model in your program is a large model (13G, link from your download.txt, [https://drive.google.com/uc?id=1049ICFtqg8_1Os7YQ8jpgQerQbMa6I_7] ). 
Did you combined the lora weights (16m) with the base model (14G)? 

My device is 4-V100x32G, and pretrained model (base model) is MAGAer13/mplug-owl-llama-7b-ft.

**Comment by GUOGUO-lab** [comment]
Update: 

I change the code of loading "adapter_model.bin":

`from peft import PeftModel, PeftConfig

peft_model_id = "./output/custom_ft/checkpoint-50/"
config = PeftConfig.from_pretrained(peft_model_id)
model = PeftModel.from_pretrained(model, peft_model_id) # load lora into base model`

This time it works.

But I'm still confused about how to load ft model in your way.

**Comment by Hyperwjf** [comment]
Hello, I'm also facing an issue with loading the mPLUG-Owl finetuned model. Could you please tell me how to load the pytorch_model.bin weights provided by the author?

**Comment by GUOGUO-lab** [comment]
> Hello, I'm also facing an issue with loading the mPLUG-Owl finetuned model. Could you please tell me how to load the pytorch_model.bin weights provided by the author?

If you already finished the finetune step and got your checkpoints (the lora part), you can do the model loading in my way.
In model_worker.py, the code first loads the original weights, then the lora part. 
Edited code(model_worker.py):

```
# Loading original weights

self.image_processor = MplugOwlImageProcessor.from_pretrained(base_model)
self.tokenizer = AutoTokenizer.from_pretrained(base_model)
self.processor = MplugOwlProcessor(self.image_processor, self.tokenizer)
self.model = MplugOwlForConditionalGeneration.from_pretrained(
     base_model,
     load_in_8bit=load_in_8bit,
     torch_dtype=torch.bfloat16 if bf16 else torch.half,  # if not support, use float16 instead of bf16
     device_map="auto"
 )
self.tokenizer = self.processor.tokenizer

# remove this part (author's way of loading lora part)

peft_config = LoraConfig(target_modules=r'.*language_model.*\.(q_proj|v_proj)', inference_mode=False, r=8,lora_alpha=32, lora_dropout=0.05)
self.model = get_peft_model(self.model, peft_config)
lora_path = 'Your lora model path'
prefix_state_dict = torch.load(lora_path, map_location='cpu')
self.model.load_state_dict(prefix_state_dict)

# add this part

from peft import PeftModel, PeftConfig
peft_model_id = "./output/custom_ft/checkpoint-50/" # the path of your lora checkpoint
config = PeftConfig.from_pretrained(peft_model_id)
self.model = PeftModel.from_pretrained(self.model, peft_model_id) # load lora into base model
```

Then you should be able to load your ft checkpoint to your base model.

**Comment by Hyperwjf** [comment]
> > Hello, I'm also facing an issue with loading the mPLUG-Owl finetuned model. Could you please tell me how to load the pytorch_model.bin weights provided by the author?
> 
> If you already finished the finetune step and got your checkpoints (the lora part), you can do the model loading in my way. In model_worker.py, the code first loads the original weights, then the lora part. Edited code(model_worker.py):
> 
> ```
> # Loading original weights
> 
> self.image_processor = MplugOwlImageProcessor.from_pretrained(base_model)
> self.tokenizer = AutoTokenizer.from_pretrained(base_model)
> self.processor = MplugOwlProcessor(self.image_processor, self.tokenizer)
> self.model = MplugOwlForConditionalGeneration.from_pretrained(
>      base_model,
>      load_in_8bit=load_in_8bit,
>      torch_dtype=torch.bfloat16 if bf16 else torch.half,  # if not support, use float16 instead of bf16
>      device_map="auto"
>  )
> self.tokenizer = self.processor.tokenizer
> 
> # remove this part (author's way of loading lora part)
> 
> peft_config = LoraConfig(target_modules=r'.*language_model.*\.(q_proj|v_proj)', inference_mode=False, r=8,lora_alpha=32, lora_dropout=0.05)
> self.model = get_peft_model(self.model, peft_config)
> lora_path = 'Your lora model path'
> prefix_state_dict = torch.load(lora_path, map_location='cpu')
> self.model.load_state_dict(prefix_state_dict)
> 
> # add this part
> 
> from peft import PeftModel, PeftConfig
> peft_model_id = "./output/custom_ft/checkpoint-50/" # the path of your lora checkpoint
> config = PeftConfig.from_pretrained(peft_model_id)
> self.model = PeftModel.from_pretrained(self.model, peft_model_id) # load lora into base model
> ```
> 
> Then you should be able to load your ft checkpoint to your base model.

Thank you very much for your reply. We did not finetune the model; we just wanted to use the pytorch_model.bin provided by the authors for comparison. Have you tried this approach?

**Comment by GUOGUO-lab** [comment]
> > > Hello, I'm also facing an issue with loading the mPLUG-Owl finetuned model. Could you please tell me how to load the pytorch_model.bin weights provided by the author?
> > 
> > 
> > If you already finished the finetune step and got your checkpoints (the lora part), you can do the model loading in my way. In model_worker.py, the code first loads the original weights, then the lora part. Edited code(model_worker.py):
> > ```
> > # Loading original weights
> > 
> > self.image_processor = MplugOwlImageProcessor.from_pretrained(base_model)
> > self.tokenizer = AutoTokenizer.from_pretrained(base_model)
> > self.processor = MplugOwlProcessor(self.image_processor, self.tokenizer)
> > self.model = MplugOwlForConditionalGeneration.from_pretrained(
> >      base_model,
> >      load_in_8bit=load_in_8bit,
> >      torch_dtype=torch.bfloat16 if bf16 else torch.half,  # if not support, use float16 instead of bf16
> >      device_map="auto"
> >  )
> > self.tokenizer = self.processor.tokenizer
> > 
> > # remove this part (author's way of loading lora part)
> > 
> > peft_config = LoraConfig(target_modules=r'.*language_model.*\.(q_proj|v_proj)', inference_mode=False, r=8,lora_alpha=32, lora_dropout=0.05)
> > self.model = get_peft_model(self.model, peft_config)
> > lora_path = 'Your lora model path'
> > prefix_state_dict = torch.load(lora_path, map_location='cpu')
> > self.model.load_state_dict(prefix_state_dict)
> > 
> > # add this part
> > 
> > from peft import PeftModel, PeftConfig
> > peft_model_id = "./output/custom_ft/checkpoint-50/" # the path of your lora checkpoint
> > config = PeftConfig.from_pretrained(peft_model_id)
> > self.model = PeftModel.from_pretrained(self.model, peft_model_id) # load lora into base model
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you should be able to load your ft checkpoint to your base model.
> 
> Thank you very much for your reply. We did not finetune the model; we just wanted to use the pytorch_model.bin provided by the authors for comparison. Have you tried this approach?

If you only need to load the [base model](https://huggingface.co/MAGAer13/mplug-owl-llama-7b-ft/tree/main), just follow the mPLUG's official code, in this project the author(Mr.Fuxiaoliu) didn't share his ft model yet. 
![image](https://github.com/FuxiaoLiu/LRV-Instruction/assets/56341774/c1ad9a31-0f75-45f8-b0ad-593b97a77cca)

This means you only need to use the first part of the code I mentioned above.

If you still face problems, please try the loading method of mplug from modelscope, or you can show your log here.

**Comment by Hyperwjf** [comment]
I want to use the finetuned mPLUG on LRV-Instruction to compare it with the base model.  I have followed the instructions of the author(Mr.Fuxiaoliu) to load it.

![WechatIMG1906](https://github.com/FuxiaoLiu/LRV-Instruction/assets/62200664/66de6e1b-00d7-4be5-93a2-c4338d132db6)

I set the base_model as the path of mplug-owl-llama-7b-ft, and lora_path as the path of pytorch_model.bin provided by the author(Mr.Fuxiaoliu). I also encounter the same problem of "Missing key(s) in state_dict: xxxxxx; Unexpected key(s) in state_dict: xxxxxx" and fail to load it.
Could you please tell me how to solve this problem? Perhaps this is due to the mplug lora model  is a large model (14G)?

**Comment by GUOGUO-lab** [comment]
> I want to use the finetuned mPLUG on LRV-Instruction to compare it with the base model. I have followed the instructions of the author(Mr.Fuxiaoliu) to load it.
> 
> ![WechatIMG1906](https://private-user-images.githubusercontent.com/62200664/304017905-66de6e1b-00d7-4be5-93a2-c4338d132db6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzM3MTksIm5iZiI6MTcwNzczMzQxOSwicGF0aCI6Ii82MjIwMDY2NC8zMDQwMTc5MDUtNjZkZTZlMWItMDBkNy00YmU1LTkzYTItYzQzMzhkMTMyZGI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwMjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTVkMGZiMjVlMGJlM2IzOWU5NThkZTE1NjVkMmQzNzJiYThhMzNkOTcxY2M2NTNhMTBiYmU5MTgxZDNlMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.55glSQ4XOA1OptWogS7FZM4JW9yJDbxkbL3592yyJrI)
> 
> I set the base_model as the path of mplug-owl-llama-7b-ft, and lora_path as the path of pytorch_model.bin provided by the author(Mr.Fuxiaoliu). I also encounter the same problem of "Missing key(s) in state_dict: xxxxxx; Unexpected key(s) in state_dict: xxxxxx" and fail to load it. Could you please tell me how to solve this problem? Perhaps this is due to the mplug lora model is a large model (14G)?

I see... you made a mistake that the "lora weight" you got from Mr.Fuxiaoliu is actually the origin base model(he didn't actually show his ft lora in his tutorial, he said "release soon", and the lora I trained by myself is less than 100m);
So, if you didn't train your own lora, please remove the code of loading lora and only use the base model.

**Comment by Hyperwjf** [comment]
> > I want to use the finetuned mPLUG on LRV-Instruction to compare it with the base model. I have followed the instructions of the author(Mr.Fuxiaoliu) to load it.
> > ![WechatIMG1906](https://private-user-images.githubusercontent.com/62200664/304017905-66de6e1b-00d7-4be5-93a2-c4338d132db6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzM3MTksIm5iZiI6MTcwNzczMzQxOSwicGF0aCI6Ii82MjIwMDY2NC8zMDQwMTc5MDUtNjZkZTZlMWItMDBkNy00YmU1LTkzYTItYzQzMzhkMTMyZGI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwMjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTVkMGZiMjVlMGJlM2IzOWU5NThkZTE1NjVkMmQzNzJiYThhMzNkOTcxY2M2NTNhMTBiYmU5MTgxZDNlMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.55glSQ4XOA1OptWogS7FZM4JW9yJDbxkbL3592yyJrI)
> > I set the base_model as the path of mplug-owl-llama-7b-ft, and lora_path as the path of pytorch_model.bin provided by the author(Mr.Fuxiaoliu). I also encounter the same problem of "Missing key(s) in state_dict: xxxxxx; Unexpected key(s) in state_dict: xxxxxx" and fail to load it. Could you please tell me how to solve this problem? Perhaps this is due to the mplug lora model is a large model (14G)?
> 
> I see... you made a mistake that the "lora weight" you got from Mr.Fuxiaoliu is actually the origin base model(he didn't actually show his ft lora in his tutorial, he said "release soon", and the lora I trained by myself is less than 100m); So, if you didn't train your own lora, please remove the code of loading lora and only use the base model.


Okay, I understand now. Thank you for your considerate and patient response! Additionally, I'm looking forward to the author releasing the lora weight soon.

**Comment by Batwho** [comment]
I'm also having the same problem in loading mPLUG-Owl finetuned model. @FuxiaoLiu Could you please confirm what @GUOGUO-lab said the provided pytorch_model.bin(14GB) is the combination of the mPLUG-Owl checkpoint with the finetuned lora weight? If so, do we need any other config.json files to load this .bin file? And maybe that also means some updates in the readme.
