### ISSUE TITLE
I wanna get the number of each 16 VL tasks in LRV-Instruction. May I ask if there are any relevant annotation files or corresponding statistical methods to get the number of Q-A pairs of each task.

### ISSUE THREAD

**Issue by schuper** [FuxiaoLiu/LRV-Instruction#21]

**Comment by FuxiaoLiu** [comment]
Thanks for questions! Although our dataset is generated by GPT4, we found GPT4 always makes mistakes when assign task name for each instruction.  I will figure it out.

**Comment by schuper** [comment]
Thanks for your response. That's an interesting question. Look forward to your breakthrough.

**Comment by schuper** [comment]
> Thanks for questions! Although our dataset is generated by GPT4, we found GPT4 always makes mistakes when assign task name for each instruction. I will figure it out.

Thanks for your response. That's an interesting question. Look forward to your breakthrough.
