### ISSUE TITLE
Evaluation set

### ISSUE THREAD

**Issue by liaoning97** [FuxiaoLiu/LRV-Instruction#4]
Firstly, I am very grateful for your wonderful work.

I wonder whether the evaluation set of the built LRV dataset corresponding to Tab. 3 released?

Thank you very much.

**Comment by FuxiaoLiu** [comment]
[Evaluation](#Evaluation)

**Comment by liaoning97** [comment]
Thank you very much for your kind reply and release for the evaluation set.
