### ISSUE TITLE
How to run validation during training?

### ISSUE THREAD

**Issue by waynemystir** [FuxiaoLiu/LRV-Instruction#5]
If I uncomment `valid_splits`, I get an error: 

`2023-07-08 12:54:47,554 [INFO] Evaluating on val.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/wayne/dev/scratch/LRV-Instruction/MiniGPT-4/train.py:110 in <module>                       │
│                                                                                                  │
│   107                                                                                            │
│   108                                                                                            │
│   109 if __name__ == "__main__":                                                                 │
│ ❱ 110 │   main()                                                                                 │
│   111                                                                                            │
│                                                                                                  │
│ /home/wayne/dev/scratch/LRV-Instruction/MiniGPT-4/train.py:106 in main                           │
│                                                                                                  │
│   103 │   runner = get_runner_class(cfg)(                                                        │
│   104 │   │   cfg=cfg, job_id=job_id, task=task, model=model, datasets=datasets                  │
│   105 │   )                                                                                      │
│ ❱ 106 │   runner.train()                                                                         │
│   107                                                                                            │
│   108                                                                                            │
│   109 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ /home/wayne/dev/scratch/LRV-Instruction/MiniGPT-4/minigpt4/runners/runner_base.py:388 in train   │
│                                                                                                  │
│   385 │   │   │   │   for split_name in self.valid_splits:                                       │
│   386 │   │   │   │   │   logging.info("Evaluating on {}.".format(split_name))                   │
│   387 │   │   │   │   │                                                                          │
│ ❱ 388 │   │   │   │   │   val_log = self.eval_epoch(                                             │
│   389 │   │   │   │   │   │   split_name=split_name, cur_epoch=cur_epoch                         │
│   390 │   │   │   │   │   )                                                                      │
│   391 │   │   │   │   │   if val_log is not None:                                                │
│                                                                                                  │
│ /home/wayne/dev/scratch/LRV-Instruction/bve/lib/python3.8/site-packages/torch/utils/_contextlib. │
│ py:115 in decorate_context                                                                       │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ /home/wayne/dev/scratch/LRV-Instruction/MiniGPT-4/minigpt4/runners/runner_base.py:470 in         │
│ eval_epoch                                                                                       │
│                                                                                                  │
│   467 │   │   │   │   During testing, we will use provided weights and skip reloading the best   │
│   468 │   │   """                                                                                │
│   469 │   │   data_loader = self.dataloaders.get(split_name, None)                               │
│ ❱ 470 │   │   assert data_loader, "data_loader for split {} is None.".format(split_name)         │
│   471 │   │                                                                                      │
│   472 │   │   # TODO In validation, you need to compute loss as well as metrics                  │
│   473 │   │   # TODO consider moving to model.before_evaluation()                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: data_loader for split val is None.`

**Comment by FuxiaoLiu** [comment]
As for inference, please refer to the inference section in the GitHub

**Comment by waynemystir** [comment]
Sorry for the confusion. I didn't ask about inference. I would like to run evaluation periodically during training. But if I uncomment or change the values on these lines, I get an error:

`https://github.com/FuxiaoLiu/LRV-Instruction/blob/main/MiniGPT-4/train_configs/minigpt4_stage2_finetune.yaml#L44-L47`
