### ISSUE TITLE
how to inference model parallelly?

### ISSUE THREAD

**Issue by pixas** [FuxiaoLiu/LRV-Instruction#6]
Nice work. I want to reproduce it on my devices but my single GPU has only 24GB memory. How to run your model on multiple GPU devices? Thank you.

**Comment by CalvinLiu12** [comment]
Can you provide the more information of your GPU? I can run the inference
successfully on single GPU within the 24GB memory.

**Comment by pixas** [comment]
Thanks for your reply. I found that it results from the `bitsandbytes` library. I have figured it out it successfully run on my device.
