### ISSUE TITLE
why code not corresponds to paper

### ISSUE THREAD

**Issue by pixas** [FuxiaoLiu/LRV-Instruction#8]
I see your code `Evaluation/evaluate.py` line 29 and  line 30 use two answers. Why do you use two answers when generating the GPT-4 scores? Are these two scores averaged to serve as the final score? Are these two answers generated with the same model with non-deterministic hparams, such as temperature or top_p?

In my perspective, your paper only mentions that you use GPT-4 to score your answer corresponding to one image and one instruction.

**Comment by CalvinLiu12** [comment]
Thanks for your question! The two answers from different models. I mean
answer1 can be from minigpt4, answer2 can be from our model. They are for
the same image and instruction. That’s why in one prompt, we can evaluate
more than one answers. Does it make sense? I will make it more clear on the
repo. If you have any questions, please let me know. Thanks!
